
" COMMON (between vim and nvim) 
source ~/.vim/common.vim

" PLUGINS
source ~/.vim/plugins.vim

" disable highlights on esc
" consider using romainl/vim-cool to solve this issue
" resorted to vim-cool, because esc fucks with ssh
" map <ESC> :noh<cr>

" Double-Esc escapes the terminal, leaving single Esc for TUI apps inside it
" (matches nvim's mapping)
tnoremap <Esc><Esc> <C-\><C-n>

" " SETTINGS
" Fix the cursor to not blink 
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"

