
" see :h defaults.vim for more details
if !has('nvim')
  unlet! skip_default_vim
  source $VIMRUNTIME/defaults.vim
endif

" PLUGINS
source ~/.vim/plugins.vim

" SHARED across vim and nvim
source ~/.vim/common.vim

